/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlsv_file;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */

public class SinhVienWindow extends javax.swing.JPanel {

    /**
     * Creates new form SinhVienWindow
     */
    String maDangNhap="";
    public SinhVienWindow() throws IOException {
        initComponents();
        
    }
    public SinhVienWindow(String ma) throws IOException {
        initComponents();
        maDangNhap=ma;
        load();
        //JOptionPane.showMessageDialog(this,maDangNhap);
    }
    public void load() throws IOException{
           String file="C:\\Users\\Admin\\Desktop\\File CSV\\18hcb_CTT001_KQ.csv";
//        path=file;
//        lineAll=file;
        File f=new File(file);
        String nameFile=f.getName();
       // lbThongBao.setText("Quản Lý Bảng Điểm Sinh Viên: "+nameFile);
        docFile(file);
        String lh="C:\\Users\\Admin\\Desktop\\File CSV\\dslop.csv";
        docFileLH(lh);
        
    }
    public void docFile(String p) throws FileNotFoundException, IOException{
        
    }
    public void loadcb1(String p) throws FileNotFoundException, IOException{
        
         DefaultComboBoxModel model=new DefaultComboBoxModel();
      
        File fileDir = new File(p);
			
		BufferedReader br = new BufferedReader(
		   new InputStreamReader(
                      new FileInputStream(fileDir), "UTF8"));
		        
        //BufferedReader br = new BufferedReader(fr);
        
        String []dataSV;
        String line = br.readLine();
        line = br.readLine();
          while(line != null){
              dataSV=line.split(",");
               model.addElement(new MonHoc(dataSV[1],dataSV[2]));
               //cbDSMH.addItem(dataSV[2].toString());
              line =br.readLine();
          }
        br.close();
       // fileDir.close();

        cbMonHoc.setModel(model);
    }
    public void docFileLH(String p) throws FileNotFoundException, IOException{
       
       File fileDir = new File(p);
			
		BufferedReader br = new BufferedReader(
		   new InputStreamReader(
                      new FileInputStream(fileDir), "UTF8"));      
        String []dataSV;
        String line = br.readLine();      
          
        line = br.readLine();
          while(line != null){
              dataSV=line.split(",");
              cbLop.addItem(dataSV[0]);
              line =br.readLine();
          }
        br.close();
       // fr.close();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbBangDiem = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cbLop = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cbMonHoc = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Thông Tin Sinh Viên");
        add(jLabel1);
        jLabel1.setBounds(310, 30, 210, 40);

        tbBangDiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbBangDiem);

        add(jScrollPane1);
        jScrollPane1.setBounds(20, 169, 850, 330);

        jLabel2.setText("Chọn Lớp ");
        add(jLabel2);
        jLabel2.setBounds(33, 92, 70, 16);

        cbLop.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbLopItemStateChanged(evt);
            }
        });
        add(cbLop);
        cbLop.setBounds(136, 89, 137, 22);

        jLabel3.setText("Môn Học");
        add(jLabel3);
        jLabel3.setBounds(356, 92, 49, 16);

        add(cbMonHoc);
        cbMonHoc.setBounds(416, 89, 180, 22);

        jButton1.setText("Xem Điểm Môn Học");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(706, 88, 145, 25);
    }// </editor-fold>//GEN-END:initComponents

    private void cbLopItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbLopItemStateChanged
        String file="C:\\Users\\Admin\\Desktop\\File CSV\\";
        String nameLop=cbLop.getSelectedItem().toString();
        //lopHoc=nameLop;
        String nameDSMH=nameLop+"_TKB.csv";
        file=file+nameDSMH;
        //JOptionPane.showMessageDialog(cbLop,file);
        if(nameDSMH!=null){
            try {
                loadcb1(file);
            } catch (IOException ex) {
                Logger.getLogger(DangKyWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cbLopItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbLop;
    private javax.swing.JComboBox cbMonHoc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbBangDiem;
    // End of variables declaration//GEN-END:variables
}
